# Generated by Django 3.1.6 on 2021-02-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_auto_20210131_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shows',
            old_name='language',
            new_name='genres',
        ),
        migrations.RenameField(
            model_name='shows',
            old_name='summary',
            new_name='overview',
        ),
        migrations.RemoveField(
            model_name='shows',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='shows',
            name='trailer',
        ),
        migrations.AddField(
            model_name='shows',
            name='first_air',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shows',
            name='last_air',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shows',
            name='next_air',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shows',
            name='rating',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shows',
            name='seasons',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shows',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
