# Generated by Django 3.1.6 on 2021-02-03 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_auto_20210202_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shows',
            old_name='genres',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='shows',
            name='country',
        ),
        migrations.RemoveField(
            model_name='shows',
            name='first_air',
        ),
        migrations.RemoveField(
            model_name='shows',
            name='image_path',
        ),
        migrations.RemoveField(
            model_name='shows',
            name='last_air',
        ),
        migrations.RemoveField(
            model_name='shows',
            name='next_air',
        ),
        migrations.RemoveField(
            model_name='shows',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='shows',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='shows',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='shows',
            name='seasons',
        ),
    ]
