# Generated by Django 3.1.6 on 2021-02-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_auto_20210202_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='type',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
