# Generated by Django 3.1.5 on 2021-02-01 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_auto_20210131_2048'),
        ('watchlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchlists',
            options={'verbose_name_plural': 'Watchlists'},
        ),
        migrations.RemoveField(
            model_name='watchlists',
            name='collection',
        ),
        migrations.AddField(
            model_name='watchlists',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='shows.shows'),
        ),
    ]
