# Generated by Django 3.1.5 on 2021-02-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_auto_20210131_2048'),
        ('watchlists', '0002_auto_20210131_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlists',
            name='collection',
        ),
        migrations.AddField(
            model_name='watchlists',
            name='collection',
            field=models.ManyToManyField(blank=True, related_name='_watchlists_collection_+', to='shows.Shows'),
        ),
    ]
