# Generated by Django 3.1.6 on 2021-02-03 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_auto_20210202_1947'),
        ('watchlists', '0003_auto_20210131_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlists',
            name='collection',
        ),
        migrations.AddField(
            model_name='watchlists',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shows.shows'),
        ),
    ]
