# Generated by Django 3.1.6 on 2021-02-04 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0004_auto_20210202_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlists',
            old_name='collection',
            new_name='show',
        ),
    ]
