# Generated by Django 3.1.6 on 2021-02-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0005_auto_20210203_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlists',
            old_name='description',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='watchlists',
            old_name='name',
            new_name='status',
        ),
        migrations.AddField(
            model_name='watchlists',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
